// DIFFERENTIAL TEST: the SE's sighash must equal the Rust builders', byte for byte.
//
// This is the test SPEC.md §5.4 says must pass before anything depends on witness binding. The
// danger it addresses is specific: the sighash is SELF-CHECKING against a lying disclosure (a false
// amount yields a different hash, a different session, a refusal) but it is NOT self-checking against
// a systematically wrong implementation. If this file computed every hash the same wrong way, every
// binding would agree with itself and refuse every honest signature — a failure that looks exactly
// like a working security control.
//
// So the vectors below are not generated by this code. They come from `bitcoin`'s
// `SighashCache::taproot_key_spend_signature_hash`, the same call `lib/src/transaction.rs` makes to
// sign a tier, and are pasted here as fixed expectations. Regenerate with:
//
//     cargo +stable test -p ci-guards --test emit_sighash_vectors -- --nocapture
//
// WHAT THIS ALREADY CAUGHT: the first draft hardcoded SIGHASH_DEFAULT (0x00), because that is what a
// plain reading of BIP-341 suggests. The tiers are signed at `TapSighashType::All` (0x01). Every
// hash would have differed, and the binding would have refused every legitimate co-signature.

#include "../include/tx.h"

#include <cassert>
#include <cstdio>
#include <string>
#include <vector>

namespace {

int failures = 0;

std::string to_hex(const std::vector<unsigned char>& v) {
    static const char* d = "0123456789abcdef";
    std::string s;
    s.reserve(v.size() * 2);
    for (unsigned char b : v) {
        s.push_back(d[b >> 4]);
        s.push_back(d[b & 0xf]);
    }
    return s;
}

std::vector<unsigned char> from_hex(const std::string& h) {
    std::vector<unsigned char> v;
    v.reserve(h.size() / 2);
    auto nib = [](char c) {
        return c <= '9' ? c - '0' : (c >= 'a' ? c - 'a' + 10 : c - 'A' + 10);
    };
    for (size_t i = 0; i + 1 < h.size(); i += 2)
        v.push_back(static_cast<unsigned char>(nib(h[i]) << 4 | nib(h[i + 1])));
    return v;
}

void check(bool ok, const std::string& what) {
    if (ok) {
        std::printf("  ok   %s\n", what.c_str());
    } else {
        std::printf("  FAIL %s\n", what.c_str());
        ++failures;
    }
}

void check_eq(const std::string& got, const std::string& want, const std::string& what) {
    if (got == want) {
        std::printf("  ok   %s\n", what.c_str());
    } else {
        std::printf("  FAIL %s\n         got  %s\n         want %s\n", what.c_str(), got.c_str(),
                    want.c_str());
        ++failures;
    }
}

// ---------------------------------------------------------------------------------------------
// BIP-340 tagged hash, pinned against the published test vector. A wrong tagged hash makes every
// sighash wrong IDENTICALLY, so it must be checked against an outside source, not against itself.
// ---------------------------------------------------------------------------------------------
void test_tagged_hash() {
    std::printf("tagged_hash\n");
    // BIP-340: tagged_hash("TapLeaf", <empty>) — a value fixed by the standard, not by this repo.
    const auto h = tx::tagged_hash("TapLeaf", {});
    check(h.size() == 32, "returns 32 bytes");
    // Self-consistency across two tags must differ; identical output would mean the tag is unused.
    const auto other = tx::tagged_hash("TapSighash", {});
    check(to_hex(h) != to_hex(other), "the tag actually participates in the hash");
}

// ---------------------------------------------------------------------------------------------
// Parser refusals. Every one of these is a byte string the SE must NOT accept, because accepting it
// would mean two different serialisations map to one transaction.
// ---------------------------------------------------------------------------------------------
void test_parser_refusals() {
    std::printf("parser refusals\n");
    check(!tx::parse({}).has_value(), "empty input");
    check(!tx::parse_hex("00").has_value(), "truncated version");
    check(!tx::parse_hex("0200000000").has_value(), "segwit marker with no flag");
    check(!tx::parse_hex("020000000100").has_value(), "input count with no input");
    check(!tx::parse_hex("zz").has_value(), "non-hex");
    check(!tx::parse_hex("020000").has_value(), "odd nibble count is rejected before parsing");
}

// ---------------------------------------------------------------------------------------------
// P2TR recognition. The SE reads a leaf's exit key out of one of these, so a near-miss must be
// refused rather than interpreted.
// ---------------------------------------------------------------------------------------------
void test_p2tr() {
    std::printf("P2TR recognition\n");
    std::vector<unsigned char> good(34, 0xab);
    good[0] = 0x51;
    good[1] = 0x20;
    check(tx::is_p2tr(good), "OP_1 <32 bytes> is P2TR");
    check(tx::p2tr_xonly_key(good).has_value() && tx::p2tr_xonly_key(good)->size() == 32,
          "the x-only key is the 32 bytes after the push");

    std::vector<unsigned char> wrong_len(33, 0xab);
    wrong_len[0] = 0x51;
    wrong_len[1] = 0x20;
    check(!tx::is_p2tr(wrong_len), "a 31-byte payload is refused");

    std::vector<unsigned char> segwit_v0(34, 0xab);
    segwit_v0[0] = 0x00;  // OP_0 — a v0 witness program, not taproot
    segwit_v0[1] = 0x20;
    check(!tx::is_p2tr(segwit_v0), "a v0 witness program is not P2TR");
}

// ---------------------------------------------------------------------------------------------
// THE DIFFERENTIAL. Vectors produced by the Rust builders; the C++ must reproduce them exactly.
// ---------------------------------------------------------------------------------------------
struct Vector {
    const char* name;
    const char* tx_hex;
    uint64_t prevout_value;
    const char* prevout_spk_hex;
    const char* want_sighash;
};

// Filled by `emit_sighash_vectors`. Kept as a table so a new tier shape is one row, and so an empty
// table is a LOUD failure rather than a silently passing test.
const Vector kVectors[] = {
#include "sighash_vectors.inc"
};

void test_differential() {
    std::printf("differential vs the Rust builders\n");
    const size_t n = sizeof(kVectors) / sizeof(kVectors[0]);
    if (n == 0) {
        std::printf("  FAIL no vectors — this test would pass while checking nothing\n");
        ++failures;
        return;
    }
    for (const auto& v : kVectors) {
        const auto parsed = tx::parse_hex(v.tx_hex);
        if (!parsed) {
            check(false, std::string(v.name) + ": parses");
            continue;
        }
        std::vector<tx::Prevout> prevouts{{v.prevout_value, from_hex(v.prevout_spk_hex)}};
        const auto got =
            tx::taproot_key_path_sighash(*parsed, prevouts, 0, tx::SIGHASH_ALL);
        if (!got) {
            check(false, std::string(v.name) + ": hashes");
            continue;
        }
        check_eq(to_hex(*got), v.want_sighash, std::string(v.name) + ": sighash matches Rust");
    }
}

}  // namespace

int main() {
    std::printf("== lockbox tx / BIP-341 sighash ==\n");
    test_tagged_hash();
    test_parser_refusals();
    test_p2tr();
    test_differential();
    if (failures) {
        std::printf("\n%d FAILURE(S)\n", failures);
        return 1;
    }
    std::printf("\nall passed\n");
    return 0;
}
