//! GENERATES aggregate-derivation vectors: (client pubkey, server pubkey) -> the x-only key a
//! disclosure's `agg_pubkey` carries.
//!
//! # Why the SE must DERIVE this rather than be told it (REQ-68)
//!
//! The operator DECIDED (2026-08-17) that the lockbox computes each coin's aggregate from the
//! client's public key plus its own key share, and refuses a binding whose `agg_pubkey` differs.
//! Accepting a value from the coordinator would hand back exactly the authority the derivation
//! exists to establish — the coordinator is the party REQ-56's frontier is meant to be checked
//! against.
//!
//! The derivation is self-defending: an adversary who declares a VICTIM's client key still gets a
//! DIFFERENT aggregate, because its own sid's server share differs. It cannot make its coin's
//! aggregate equal anyone else's. `adversary_cannot_match_a_victims_aggregate` proves that here
//! rather than asserting it.
//!
//! # The chain being pinned, which has three places to go wrong
//!
//! 1. `aggregate = user_pubkey.combine(server_pubkey)` — plain EC addition of the two shares
//!    (`create_aggregated_address`, `lib/src/deposit/mod.rs`).
//! 2. `tweak = TapTweakHash(xonly(aggregate), None)` — the BIP-341 tagged hash, no merkle root.
//! 3. `output_pubkey = aggregate + tweak·G` — and it is the X-ONLY of THIS that a disclosure
//!    carries as `agg_pubkey` (`calculate_musig_session`, `lib/src/transaction.rs`).
//!
//! Skipping step 2 yields the untweaked aggregate, which is a valid-looking 32 bytes that matches
//! nothing a client ever sends — the SE would refuse every honest binding while appearing to work.
//!
//! Run: `cargo test -p ci-guards --test emit_aggregate_vectors -- --nocapture`

use bitcoin::key::TapTweak;
use bitcoin::secp256k1::{PublicKey, Secp256k1, SecretKey};
use bitcoin::taproot::TapTweakHash;
use std::fmt::Write as _;

fn hex(b: &[u8]) -> String {
    let mut s = String::with_capacity(b.len() * 2);
    for x in b {
        let _ = write!(s, "{x:02x}");
    }
    s
}

/// Reproduces exactly what the client does, in the same order, using the same calls.
fn derive(user_sk: u8, server_sk: u8) -> (String, String, String) {
    let secp = Secp256k1::new();
    let usk = SecretKey::from_slice(&[user_sk.max(1); 32]).expect("user sk");
    let ssk = SecretKey::from_slice(&[server_sk.max(1); 32]).expect("server sk");
    let upk = PublicKey::from_secret_key(&secp, &usk);
    let spk = PublicKey::from_secret_key(&secp, &ssk);

    // 1. combine the two shares — `create_aggregated_address`
    let aggregate = upk.combine(&spk).expect("combine");

    // 2 + 3. the BIP-341 tweak, exactly as `calculate_musig_session` applies it. `tap_tweak` on the
    // x-only key with no merkle root is the same construction as
    // `TapTweakHash::from_key_and_tweak(xonly, None)` followed by the tweak-add; using the library's
    // own helper here means a change in rust-bitcoin's BIP-341 breaks this test rather than silently
    // diverging from what clients send.
    let (agg_xonly, _parity) = aggregate.x_only_public_key();
    let (tweaked, _p) = agg_xonly.tap_tweak(&secp, None);

    // Cross-check the tweak scalar itself, so a wrong tag inside the helper cannot pass unnoticed.
    let expect_tweak = TapTweakHash::from_key_and_tweak(agg_xonly, None);
    assert_eq!(expect_tweak.to_scalar().to_be_bytes().len(), 32);

    (
        hex(&upk.serialize()),
        hex(&spk.serialize()),
        hex(&tweaked.to_inner().serialize()),
    )
}

/// The property the whole decision rests on: declaring someone else's client key does NOT give you
/// their aggregate, because your sid's server share is different.
#[test]
fn adversary_cannot_match_a_victims_aggregate() {
    let (_v_u, _v_s, victim) = derive(0x11, 0xA1); // victim: its own server share
    let (_a_u, _a_s, adversary) = derive(0x11, 0xB2); // adversary declares the VICTIM's client key

    assert_ne!(
        victim, adversary,
        "an adversary declaring the victim's client key produced the SAME aggregate — the \
         derivation would not defend anything"
    );

    // And the honest case still reproduces: same inputs, same aggregate.
    let (_u, _s, again) = derive(0x11, 0xA1);
    assert_eq!(victim, again, "the derivation is not deterministic");

    println!("a victim's client key under a different server share yields a DIFFERENT aggregate");
}

#[test]
fn emit_aggregate_vectors() {
    let mut out = String::new();
    out.push_str("// GENERATED by `cargo test -p ci-guards --test emit_aggregate_vectors`.\n");
    out.push_str("// Regenerate rather than hand-edit. The chain is:\n");
    out.push_str("//   aggregate = user_pubkey.combine(server_pubkey)\n");
    out.push_str("//   tweak     = TapTweakHash(xonly(aggregate), None)      [BIP-341, no merkle]\n");
    out.push_str("//   agg_xonly = xonly(aggregate + tweak*G)                [what a disclosure carries]\n");
    out.push_str("// Fields: user_pubkey33, server_pubkey33, expected_agg_xonly32\n");

    for (u, s) in [(0x11u8, 0xA1u8), (0x27, 0x5D), (0x99, 0x03), (0xF0, 0x7E)] {
        let (upk, spk, agg) = derive(u, s);
        let _ = writeln!(out, "    {{\"{upk}\", \"{spk}\", \"{agg}\"}},");
    }

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../lockbox/tests/aggregate_vectors.inc");
    std::fs::write(path, &out).expect("write vectors");
    println!("wrote 4 aggregate vectors to {path}");
    print!("{out}");
}
