//! Emit blinded MuSig2 **session** vectors for the lockbox's witness-binding differential.
//!
//! # The assumption this exists to test
//!
//! Witness binding rebuilds the signing session inside the SE and byte-compares it against the 133
//! bytes the client asked it to sign. That comparison rests on an assumption taken from the route's
//! length check rather than from the fork's serialisation code: **that `secp256k1_musig_session`'s
//! in-memory layout is exactly what `MusigSession::serialize()` produces.**
//!
//! If that is wrong, the compare fails for every honest request and the SE refuses everything. A safe
//! direction to fail in, still wrong — and self-consistent, so nothing inside the C++ would notice.
//! It is the same shape as the `SIGHASH_DEFAULT`-vs-`ALL` bug: an implementation that agrees with
//! itself and rejects reality.
//!
//! So the vectors here come from the Rust client's own call chain — the one `calculate_musig_session`
//! uses — and are written where the C++ test includes them:
//!
//! ```text
//! cargo +stable test -p ci-guards --test emit_session_vectors -- --nocapture
//! ```
//!
//! Each vector carries every input the SE receives in a disclosure (aggregate nonce, output key,
//! sighash, blinding factor, output tweak) plus the serialised session the client sends. The C++ must
//! reproduce the latter from the former.

use secp256k1_zkp::musig::{
    blinded_musig_pubkey_xonly_tweak_add, new_musig_nonce_pair, BlindingFactor, MusigAggNonce,
    MusigPubNonce, MusigSecNonce, MusigSession, MusigSessionId,
};
use secp256k1_zkp::{Message, PublicKey, Secp256k1, SecretKey};
use std::fmt::Write as _;

fn hex(b: &[u8]) -> String {
    b.iter().fold(String::new(), |mut s, x| {
        let _ = write!(s, "{x:02x}");
        s
    })
}

/// One session built from deterministic material, reported with every input beside the output.
///
/// Determinism matters twice: a vector that changes per run cannot be pasted into a C++ table, and a
/// test that regenerates its own expectations checks nothing.
fn one_vector(seed: u8) -> (String, String, String, String, String, String) {
    let secp = Secp256k1::new();

    let sk1 = SecretKey::from_slice(&[seed.max(1); 32]).expect("sk1");
    let sk2 = SecretKey::from_slice(&[seed.wrapping_add(0x40).max(1); 32]).expect("sk2");
    let pk1 = PublicKey::from_secret_key(&secp, &sk1);
    let pk2 = PublicKey::from_secret_key(&secp, &sk2);

    let id1 = MusigSessionId::assume_unique_per_nonce_gen([seed.wrapping_add(1).max(1); 32]);
    let id2 = MusigSessionId::assume_unique_per_nonce_gen([seed.wrapping_add(2).max(1); 32]);
    let seed_msg = Message::from_slice(&[seed.wrapping_add(3).max(1); 32]).expect("seed msg");

    let (_s1, p1): (MusigSecNonce, MusigPubNonce) =
        new_musig_nonce_pair(&secp, id1, None, Some(sk1), pk1, Some(seed_msg), None).expect("n1");
    let (_s2, p2): (MusigSecNonce, MusigPubNonce) =
        new_musig_nonce_pair(&secp, id2, None, Some(sk2), pk2, Some(seed_msg), None).expect("n2");

    let aggnonce = MusigAggNonce::new(&secp, &[p1, p2]);

    // Stands in for the sighash the SE recomputes from the disclosed transaction.
    let sighash = [seed.wrapping_add(7).max(1); 32];
    let msg = Message::from_slice(&sighash).expect("sighash msg");

    let blinding = BlindingFactor::from_slice(&[seed.wrapping_add(9).max(1); 32]).expect("blinding");

    // The output key and tweak come from the SAME derivation the client uses, rather than from
    // invented bytes: `blinded_musig_pubkey_xonly_tweak_add` returns the tweaked output key and the
    // `Tweak` the session is built with. Using the real path means a change to it breaks this test
    // rather than silently producing vectors nobody's code would ever generate.
    let tweak_in = SecretKey::from_slice(&[seed.wrapping_add(11).max(1); 32]).expect("tweak in");
    let (_parity, output_pubkey, out_tweak) =
        blinded_musig_pubkey_xonly_tweak_add(&secp, &pk1, tweak_in);

    let session = MusigSession::new_blinded_without_key_agg_cache(
        &secp, &output_pubkey, aggnonce, msg, None, &blinding, out_tweak,
    );

    (
        hex(&output_pubkey.serialize()),
        hex(&aggnonce.serialize()),
        hex(&sighash),
        hex(blinding.as_bytes()),
        hex(out_tweak.as_ref()),
        // THE WIRE FORM. `calculate_musig_session` sends
        // `remove_fin_nonce_from_session().serialize()`, not the raw session — so this is what the SE
        // must reproduce. Emitting the raw session here is what made the first version of this test
        // agree with itself and prove nothing.
        hex(&session.remove_fin_nonce_from_session().serialize()),
    )
}

#[test]
fn emit_session_vectors() {
    let mut out = String::new();
    out.push_str("// GENERATED by `cargo test -p ci-guards --test emit_session_vectors`.\n");
    out.push_str("// Regenerate rather than hand-edit. Produced by the same blinded-session call the\n");
    out.push_str("// client makes in `calculate_musig_session` (lib/src/transaction.rs).\n");
    out.push_str("// Fields: agg_pubkey, agg_nonce, sighash, blinding_factor, out_tweak, session\n");

    let mut session_len = 0usize;
    for seed in [0x11u8, 0x53, 0xa7] {
        let (pk, nonce, sighash, blinding, tweak, session) = one_vector(seed);
        session_len = session.len() / 2;
        writeln!(
            out,
            "    {{\"{pk}\", \"{nonce}\", \"{sighash}\", \"{blinding}\", \"{tweak}\", \"{session}\"}},"
        )
        .unwrap();
    }

    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("lockbox/tests/session_vectors.inc");
    std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
    std::fs::write(&dest, &out).unwrap();
    println!("wrote 3 session vectors to {}", dest.display());
    println!("serialized session length: {session_len} bytes");
    println!("{out}");

    // The route accepts exactly 133 bytes. A different length means the SE's byte-compare is
    // comparing the wrong thing and witness binding cannot be correct as written.
    assert_eq!(
        session_len, 133,
        "the client's serialized session is {session_len} bytes, not the 133 the route accepts and \
         the SE compares against — witness binding's byte-compare rests on a false assumption"
    );
}
