//! Emit BIP-341 sighash vectors for the lockbox's C++ differential test.
//!
//! The SE's `taproot_key_path_sighash` must equal what the Rust builders compute, byte for byte. It
//! cannot be checked against itself: a systematically wrong implementation agrees with itself
//! perfectly and would refuse every honest co-signature while looking like a working control.
//!
//! So this test computes the hashes with the SAME call `lib/src/transaction.rs` uses to sign a
//! tier — `SighashCache::taproot_key_spend_signature_hash` at `TapSighashType::All` — and writes
//! them where the C++ test includes them. Run it and the vectors regenerate:
//!
//! ```text
//! cargo +stable test -p ci-guards --test emit_sighash_vectors -- --nocapture
//! ```
//!
//! The shapes below are the ones the tiers actually take: the TRIGGER (no relative lock,
//! `0xFFFF_FFFD`), an EXTENSION/STATE rung (a real CSV), and a multi-output spine `SP` (several
//! payload outputs plus the P2A anchor). If a new tier shape appears, add a row here first — the C++
//! side reads whatever this writes.

use bitcoin::absolute::LockTime;
use bitcoin::hashes::Hash;
use bitcoin::sighash::{Prevouts, SighashCache, TapSighashType};
use bitcoin::{Amount, OutPoint, ScriptBuf, Sequence, Transaction, TxIn, TxOut, Txid, Witness};
use std::fmt::Write as _;

/// A P2TR scriptPubKey over a deterministic 32-byte key, so the vectors are reproducible.
fn p2tr(seed: u8) -> ScriptBuf {
    let mut spk = vec![0x51, 0x20];
    spk.extend_from_slice(&[seed; 32]);
    ScriptBuf::from_bytes(spk)
}

fn outpoint(seed: u8, vout: u32) -> OutPoint {
    OutPoint { txid: Txid::from_byte_array([seed; 32]), vout }
}

struct Case {
    name: &'static str,
    tx: Transaction,
    prevout: TxOut,
}

fn cases() -> Vec<Case> {
    // TRIGGER: v3, one input at TRIGGER_SEQUENCE (no relative timelock), payload + P2A anchor.
    let trigger = Transaction {
        version: bitcoin::transaction::Version(3),
        lock_time: LockTime::ZERO,
        input: vec![TxIn {
            previous_output: outpoint(0x11, 0),
            script_sig: ScriptBuf::new(),
            sequence: Sequence(0xFFFF_FFFD),
            witness: Witness::new(),
        }],
        output: vec![
            TxOut { value: Amount::from_sat(99_000), script_pubkey: p2tr(0x22) },
            TxOut { value: Amount::from_sat(240), script_pubkey: ScriptBuf::from_bytes(vec![0x51, 0x02, 0x4e, 0x73]) },
        ],
    };

    // RUNG: a real relative timelock, the shape an extension or state tier takes.
    let rung = Transaction {
        version: bitcoin::transaction::Version(3),
        lock_time: LockTime::ZERO,
        input: vec![TxIn {
            previous_output: outpoint(0x33, 0),
            script_sig: ScriptBuf::new(),
            sequence: Sequence(720),
            witness: Witness::new(),
        }],
        output: vec![
            TxOut { value: Amount::from_sat(98_385), script_pubkey: p2tr(0x44) },
            TxOut { value: Amount::from_sat(240), script_pubkey: ScriptBuf::from_bytes(vec![0x51, 0x02, 0x4e, 0x73]) },
        ],
    };

    // SPINE: several payload outputs plus the anchor — the multi-output shape a split state takes,
    // and the one most likely to expose an output-serialisation bug.
    let mut spine_outputs = Vec::new();
    for i in 0..4u8 {
        spine_outputs.push(TxOut { value: Amount::from_sat(20_000 + i as u64), script_pubkey: p2tr(0x50 + i) });
    }
    spine_outputs.push(TxOut { value: Amount::from_sat(240), script_pubkey: ScriptBuf::from_bytes(vec![0x51, 0x02, 0x4e, 0x73]) });
    let spine = Transaction {
        version: bitcoin::transaction::Version(3),
        lock_time: LockTime::ZERO,
        input: vec![TxIn {
            previous_output: outpoint(0x66, 1),
            script_sig: ScriptBuf::new(),
            sequence: Sequence(0),
            witness: Witness::new(),
        }],
        output: spine_outputs,
    };

    // NON-ZERO LOCKTIME: the sighash commits to it, so a shape that carries one must be covered or a
    // locktime bug hides behind three vectors that all use zero.
    let mut locked = rung.clone();
    locked.lock_time = LockTime::from_height(800_000).unwrap();

    vec![
        Case { name: "trigger", tx: trigger, prevout: TxOut { value: Amount::from_sat(100_000), script_pubkey: p2tr(0x99) } },
        Case { name: "rung_csv720", tx: rung, prevout: TxOut { value: Amount::from_sat(99_000), script_pubkey: p2tr(0xaa) } },
        Case { name: "spine_4_payloads", tx: spine, prevout: TxOut { value: Amount::from_sat(100_000), script_pubkey: p2tr(0xbb) } },
        Case { name: "rung_locktime_800000", tx: locked, prevout: TxOut { value: Amount::from_sat(99_000), script_pubkey: p2tr(0xcc) } },
    ]
}

#[test]
fn emit_sighash_vectors() {
    let mut out = String::new();
    out.push_str("// GENERATED by `cargo test -p ci-guards --test emit_sighash_vectors`.\n");
    out.push_str("// Hand edits are pointless: regenerate instead. The values come from\n");
    out.push_str("// `SighashCache::taproot_key_spend_signature_hash` at `TapSighashType::All`,\n");
    out.push_str("// the same call `lib/src/transaction.rs` makes to sign a tier.\n");

    for c in cases() {
        let hash = SighashCache::new(&c.tx)
            .taproot_key_spend_signature_hash(0, &Prevouts::All(&[c.prevout.clone()]), TapSighashType::All)
            .expect("sighash");

        let tx_hex = bitcoin::consensus::encode::serialize_hex(&c.tx);
        let spk_hex: String =
            c.prevout.script_pubkey.as_bytes().iter().fold(String::new(), |mut s, b| {
                let _ = write!(s, "{b:02x}");
                s
            });

        writeln!(
            out,
            "    {{\"{}\", \"{}\", {}, \"{}\", \"{}\"}},",
            c.name,
            tx_hex,
            c.prevout.value.to_sat(),
            spk_hex,
            hash
        )
        .unwrap();
    }

    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("lockbox/tests/sighash_vectors.inc");
    std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
    std::fs::write(&dest, &out).unwrap();
    println!("wrote {} vectors to {}", cases().len(), dest.display());
    println!("{out}");

    assert!(!cases().is_empty(), "an empty vector set would make the C++ differential vacuous");
}
